const String SERVER_FAILURE_MESSAGE = 'SERVER_FAILURE_MESSAGE';
const String CACHED_FAILURE_MESSAGE = 'CACHED_FAILURE_MESSAGE';
const String UNEXPECTED_FAILURE_MESSAGE = 'UNEXPECTED_FAILURE_MESSAGE';
const String CACHED_PERSONS_LIST = 'CACHED_PERSONS_LIST';
